name: Build Kivy APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker build -t kivy-apk .
        docker run --rm -v ${{ github.workspace }}:/app kivy-apk
